# Generated by Django 4.2.1 on 2023-05-22 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='files/business')),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('convenience', 'Convenience'), ('grocery', 'Grocery'), ('alcohol', 'Alcohol'), ('pets', 'Pets'), ('flowers', 'Flowers'), ('shipping', 'Shipping'), ('packages', 'Packages'), ('gifts', 'Gifts')], max_length=255)),
                ('food_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fast_food', 'Fast Food'), ('mexican', 'Mexican'), ('desserts', 'Desserts'), ('chicken', 'Chicken'), ('burgers', 'Burgers'), ('soup', 'Soup'), ('snack', 'Snack'), ('pizza', 'Pizza'), ('drinks', 'Drinks'), ('chinese', 'Chinese'), ('sandwiches', 'Sandwiches'), ('smoothie', 'Smoothie'), ('coffee', 'Coffee'), ('healthy', 'Healthy'), ('breakfast', 'Breakfast'), ('salad', 'Salad'), ('italian', 'Italian'), ('seafood', 'Seafood'), ('barbeque', 'Barbeque'), ('bakery', 'Bakery'), ('asian', 'Asian'), ('thai', 'Thai')], max_length=255)),
                ('dashboard', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('national', 'National Favorties'), ('breakfast', 'Best of Breakfast'), ('lunch', 'Best of Lumch'), ('convenience', 'Convenience & Drugstores'), ('grocery', 'Grocery')], max_length=255)),
                ('favorite', models.BooleanField(default=False)),
                ('rating_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('reviews', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('expensive_rating', models.CharField(choices=[('$', 'Cheap'), ('$$', 'Budget'), ('$$$', 'Expensive')])),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prices', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=500, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.business')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ManyToManyField(through='instadash.ItemCart', to='instadash.cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(through='instadash.OrderHistory', to='instadash.user'),
        ),
    ]
