# Generated by Django 4.2.1 on 2023-05-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='files/item'),
        ),
    ]
