# Generated by Django 4.2.1 on 2023-05-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('expensive_rating', models.CharField(choices=[('$', 'Cheap'), ('$$', 'Budget'), ('$$$', 'Expensive')])),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prices', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=500, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.business')),
                ('carts', models.ManyToManyField(to='instadash.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(through='instadash.OrderHistory', to='instadash.user'),
        ),
    ]
