# Generated by Django 4.2.1 on 2023-05-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0002_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='files/ad')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instadash.business')),
            ],
        ),
    ]
