# Generated by Django 4.2.1 on 2023-07-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0002_category_dashboard_foodtype_storetype_storedashboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='rating_score',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ratings',
        ),
    ]
