# Generated by Django 4.2.1 on 2023-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0003_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='bg_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='button_color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
