# Generated by Django 4.2.1 on 2023-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0004_ad_bg_color_ad_button_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='border_color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
