# Generated by Django 4.2.1 on 2023-05-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0005_ad_border_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='business',
        ),
        migrations.CreateModel(
            name='BusinessAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.ad')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.business')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='ads',
            field=models.ManyToManyField(through='instadash.BusinessAd', to='instadash.business'),
        ),
    ]
