# Generated by Django 4.2.1 on 2023-08-17 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0006_rename_ads_ad_stores_category_stores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='forHome',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=4000, null=True)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=16)),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.category')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instadash.dashboard')),
            ],
        ),
    ]
