# Generated by Django 4.2.1 on 2023-08-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0008_alter_dashboard_forhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
