# Generated by Django 4.2.1 on 2023-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0012_orderhistory_remove_cart_iscart_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='inCart',
            field=models.BooleanField(default=True),
        ),
    ]
