# Generated by Django 4.2.1 on 2023-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0013_cart_incart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='destination_lat',
            field=models.DecimalField(decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='destination_lng',
            field=models.DecimalField(decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='origin_lat',
            field=models.DecimalField(decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='origin_lng',
            field=models.DecimalField(decimal_places=13, max_digits=16, null=True),
        ),
    ]
