# Generated by Django 4.2.1 on 2023-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0014_orderhistory_destination_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='place_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
