# Generated by Django 4.2.1 on 2023-09-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0015_orderhistory_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='place_id',
        ),
    ]
