# Generated by Django 4.2.1 on 2023-09-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0017_orderhistory_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='Total',
            new_name='total',
        ),
    ]
