# Generated by Django 4.2.1 on 2023-09-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0019_orderhistory_totalquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='totalQuantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
