# Generated by Django 4.2.1 on 2023-09-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadash', '0020_alter_orderhistory_totalquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstore',
            name='date_saved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
